#include "logging/steav_logger.h"
#include "vm/vm.h"
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>

// generated by CMakeLists.txt at configure time, from build_info.h.in
#include "build_info.h"

static const char *BANNER = R"STEAV(     _                   _____ _____ 
 ___| |_ ___  __ ___   __\_   \\_   \
/ __| __/ _ \/ _` \ \ / / / /\/ / /\/
\__ \ ||  __/ (_| |\ V /\/ /_/\/ /_  
|___/\__\___|\__,_| \_/\____/\____/  
     The Cooler SteavScript !                                   
)STEAV";

static void print_version() {
  printf("%s", BANNER);
  printf("steav %s (%s)\n", STEAV_VERSION, STEAV_GIT_COMMIT);
  printf("  compiler  %s\n", STEAV_COMPILER);
  printf("  platform  %s\n", STEAV_BUILD_PLATFORM);
  printf("  build     %s, C++%ld\n", STEAV_BUILD_TYPE,
         (__cplusplus / 100) % 100);
  printf("  options   %s\n", STEAV_BUILD_OPTIONS);
}

int main(int argc, char **argv) {
  if (argc == 2 &&
      (strcmp(argv[1], "--version") == 0 || strcmp(argv[1], "-v") == 0)) {
    print_version();
    return 0;
  }
  bool dump = argc == 3 && strcmp(argv[1], "--dump") == 0;
  if (argc != 2 && !dump) {
    fprintf(stderr, "usage: steav <path.sts>\n       steav --dump <path.sts>\n"
                    "       steav --version\n");
    return 64;
  }
  const char *path = argv[argc - 1];

  std::ifstream file(path);
  if (!file) {
    char open_err_str[512];
    snprintf(open_err_str, sizeof(open_err_str), "could not open \"%s\"",
             path);
    STEAV_LOGGING_LOG(open_err_str, STEAV_LOGGING_FILE_NOT_FOUND);
    return 74;
  }
  std::stringstream buf;
  buf << file.rdbuf();
  std::string source = buf.str();

  steav_vm::VM vm;
  SteavStatus status = dump ? vm.disassemble(source.c_str(), path)
                            : vm.interpret(source.c_str(), path);
  if (status == STEAV_LOGGING_COMPILE_ERROR)
    return 65;
  if (status == STEAV_LOGGING_RUNTIME_ERROR)
    return 70;
  return 0;
}
